# After adding new repo, run 'pre-commit install'. This will add pre commit hook for the newly added repo.
# To uninstall pre commit hooks, run 'pre-commit uninstall'

repos:
  # Hook installed locally
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8

  # Hook not yet installed locally
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        args: [ "-r", "." ]
